### ISSUE TITLE
[Feature]: Add support for `VersionPrefix` in csproj

### ISSUE THREAD

**Issue by ctolkien** [bbonkr/get-version-action#269]
### Please describe new feature

I want this feature as all my packages use `VersionPrefix` instead of `Version`. We use this to more easily combine this with the `VersionSuffix` which can easily be passed as a msbuild argument.

**Comment by bbonkr** [comment]
@ctolkien 

Thanks to you, I realized that the version string is `{version-prefix}-{version-suffix}`.

I'll change trying to find version string as follow:

1. find version element. 
    1. Use a version string found.
2. if it does not exists, try to find `version-prefix`, `version-suffix`.
    1. Combine these strings.

I'll request your review as soon as possible.

Thank you for your contribution.

**Comment by bbonkr** [comment]
@ctolkien.

Thanks for the suggestion.

Reopen this issue if it's not enough.

### Changes

Add handling of version information in the `.csproj` file.

1. Find the `Version` element.
2. Use the string from the `Version` element if it exists.
3. If there is no string in the `Version` element, find the `VersionPrefix` element and the `VersionSuffix` element.
4. If only the `VersionPrefix` element is present, use `VersionPrefix` as the result.
5. If text from both the `VersionPrefix` and `VersioinSuffix` elements are present, use the combination, such as `{VersionPrefix}-{VersioinSuffix}`.
6. If neither the `Version` element, `VersionPrefix` element, nor `VersionSuffix` element exists, use an empty string as the result.

> If the `VersionPrefix` element is not present but the `VersionSuffix` element is, the string in the `VersionSuffix` element is ignored.


- https://github.com/bbonkr/get-version-action/releases/tag/v1.2.0
- https://github.com/bbonkr/get-version-action/pull/271
